### ISSUE TITLE
Bot not starting on windows 10

### ISSUE THREAD

**Issue by Repressoh** [BotsCord/BotCreator#2]
I am trying to start the bot, the .py script works fine but when i select run from the menu ( after inserting the bot token ) it crash.
I have python 3.7.9 from microsoft store on Windows 10 build 19044.1586.

> ✔️  What do you want to do? arrow keys to move and enter to select Run
Traceback (most recent call last):
  File ".\main.py", line 170, in <module>
    menu()
  File ".\main.py", line 145, in menu
    amark=emoji.emojize(":check_mark: "),
  File "C:\Users\casealby\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\InquirerPy\base\simple.py", line 330, in execute
    result = self._run()
  File "C:\Users\casealby\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\InquirerPy\base\complex.py", line 205, in _run
    return self.application.run()
  File "C:\Users\casealby\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\prompt_toolkit\application\application.py", line 938, in run
    self.run_async(pre_run=pre_run, set_exception_handler=set_exception_handler)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 562, in run_until_complete
    self._check_closed()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'Application.run_async' was never awaited
PS C:\Users\casealby\Downloads\BotCreator-master>

**Comment by StarNumber12046** [comment]
I tested with python 3.7.9 and 3.9 and I can't reproduce, do you use releases or source code build?

**Comment by Repressoh** [comment]
Source code, beacause release don't start

**Comment by StarNumber12046** [comment]
could you try another python version?

**Comment by StarNumber12046** [comment]
I can't reproduce the bug.

**Comment by Repressoh** [comment]
I try today on a fresh install of windows. But I think that the fault is of Powershell on the paste of the token. I will update you today or tomorrow

**Comment by ImAndrew0** [comment]
same error

**Comment by ImAndrew0** [comment]
Traceback (most recent call last):
  File "C:\Users\name\BotCreator\main.py", line 170, in <module>
    menu()
  File "C:\Users\name\BotCreator\main.py", line 141, in menu
    choice = inquirer.select(
TypeError: ListPrompt.__init__() got an unexpected keyword argument 'amark'

**Comment by StarNumber12046** [comment]
Try removing amark="..."

**Comment by ImAndrew0** [comment]
ok now works

**Comment by ImAndrew0** [comment]
same error, async never awaited

**Comment by StarNumber12046** [comment]
Remove emoji=... and all references

**Comment by Repressoh** [comment]
sorry for the long wait. I retryed today and this is the error i get 

> ✔️  What do you want to do? arrow keys to move and enter to select Run
Traceback (most recent call last):
  File "C:\Users\Casea\OneDrive\Desktop\BotCreator-master\main.py", line 170, in <module>
    menu()
  File "C:\Users\Casea\OneDrive\Desktop\BotCreator-master\main.py", line 146, in menu
    ).execute()
  File "C:\Users\Casea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\InquirerPy\base\simple.py", line 330, in execute
    result = self._run()
  File "C:\Users\Casea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\InquirerPy\base\complex.py", line 205, in _run
    return self.application.run()
  File "C:\Users\Casea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prompt_toolkit\application\application.py", line 936, in run
    return loop.run_until_complete(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 621, in run_until_complete
    self._check_closed()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001DE1EE50550>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'Application.run_async' was never awaited
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001DE1EE50550>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 750, in call_soon
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
PS C:\Users\Casea\OneDrive\Desktop\BotCreator-master>


python 3.10.4 from microsoft store on Latest windows 11 Dev insider build and Windows Terminal

**Comment by StarNumber12046** [comment]
hm, I'm gonna fix this

**Comment by StarNumber12046** [comment]
Seems a dependency issue

**Comment by CasealbyOfficial** [comment]
Maybe create a requirements.txt file for pip with dependencies
